sudo: required
services:
  - docker

before_install:
  - docker build -t kajvalia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kajvalia/react-test npm test

after_success:
  - docker build -t kajvalia/multi-client ./client
  - docker build -t kajvalia/multi-nginx ./nginx
  - docker build -t kajvalia/multi-server ./server
  - docker build -t kajvalia/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
  # Push our images to docker hub
  - docker push kajvalia/multi-client
  - docker push kajvalia/multi-nginx
  - docker push kajvalia/multi-server
  - docker push kajvalia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-235541341898
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY